// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// IMPORTANT: this file is auto generated. Please do not edit this file.
/* istanbul ignore file */
export default `:host{.background-bar-container{display:none}.timeline-tree-view devtools-toolbar{border:0}.timeline-tree-view .data-grid .odd{background:none}.timeline-tree-view .data-grid{border-width:0!important;th{background-color:var(--sys-color-cdt-base-container);font-weight:var(--ref-typeface-weight-medium);text-align:center;&.site-column{text-align:left}}tr .numeric-column,
    tr .site-column{border-left:none;border-bottom:var(--sys-size-1) solid var(--sys-color-divider);contain:strict;padding:0;line-height:21px}.bottom-filler-td,
    th.sortable{border:none}tr{height:22px}devtools-button{display:inline-flex;visibility:hidden;margin:0 8px 0 4px;vertical-align:top}tr.revealed:hover,
    tr.selected{devtools-button{visibility:visible}}.corner,
    &.data-grid-fits-viewport .corner{display:none}.data-grid-resizer:hover{background:linear-gradient(to right,transparent,transparent 2px,var(--sys-color-divider) 2px,var(--sys-color-divider) 3px,transparent 3px) no-repeat 0 0 /100% 100%}}.widget.vbox.timeline-tree-view{max-width:min(100%,550px);min-width:350px;padding:0 0 0 var(--sys-size-6)}.has-max-rows{max-height:calc(21px + (var(--max-rows) * 22px));padding:var(--sys-size-3)}.timeline-tree-view .data-grid .name-container{display:block;padding-left:2px;.activity-name{display:inline}.activity-icon-container{display:none}.entity-badge{margin-left:var(--sys-size-4);font-weight:var(--ref-typeface-weight-medium);padding:0 var(--sys-size-2);background-color:var(--sys-color-tonal-container);border-radius:var(--sys-shape-corner-extra-small);height:16px;line-height:16px;font-size:var(--sys-typescale-body5-size);display:inline-block}}}.empty-table{display:none}
/*# sourceURL=${import.meta.resolve('./thirdPartyTreeView.css')} */`;