sonar.projectName=remote-debug-tools
sonar.projectKey=remote-debug-tools
sonar.projectBaseDir=.
sonar.sources=client,apps,sdk,libs
sonar.inclusions=\
client/**/*.{ts,tsx},\
apps/**/*.{ts,tsx},\
sdk/**/*.{ts,tsx},\
libs/**/*.{ts,tsx}

sonar.exclusions=node_modules,devtools-frontend

sonar.sourceEncoding=UTF-8
sonar.language=ts
sonar.verbose=false
sonar.qualitygate.wait=true

# Configure your SonarQube server URL
# sonar.host.url=https://your-sonarqube-server.com