var L=Object.defineProperty;var T=(t,e)=>{for(var o in e)L(t,o,{get:e[o],enumerable:!0})};var S={};T(S,{SuggestionInput:()=>i});import*as x from"./../code_highlighter/code_highlighter.js";var f=`.token-variable{color:var(--sys-color-token-variable)}.token-property{color:var(--sys-color-token-property)}.token-type{color:var(--sys-color-token-type)}.token-variable-special{color:var(--sys-color-token-variable-special)}.token-definition{color:var(--sys-color-token-definition)}.token-builtin{color:var(--sys-color-token-builtin)}.token-number{color:var(--sys-color-token-number)}.token-string{color:var(--sys-color-token-string)}.token-string-special{color:var(--sys-color-token-string-special)}.token-atom{color:var(--sys-color-token-atom)}.token-keyword{color:var(--sys-color-token-keyword)}.token-comment{color:var(--sys-color-token-comment)}.token-meta{color:var(--sys-color-token-meta)}.token-invalid{color:var(--sys-color-error)}.token-tag{color:var(--sys-color-token-tag)}.token-attribute{color:var(--sys-color-token-attribute)}.token-attribute-value{color:var(--sys-color-token-attribute-value)}.token-inserted{color:var(--sys-color-token-inserted)}.token-deleted{color:var(--sys-color-token-deleted)}.token-heading{color:var(--sys-color-token-variable-special);font-weight:bold}.token-link{color:var(--sys-color-token-variable-special);text-decoration:underline}.token-strikethrough{text-decoration:line-through}.token-strong{font-weight:bold}.token-emphasis{font-style:italic}
/*# sourceURL=${import.meta.resolve("./codeHighlighter.css")} */`;import*as R from"./../../lit/lit.js";import*as h from"./../../visual_logging/visual_logging.js";var p=`*{box-sizing:border-box;font-size:inherit;margin:0;padding:0}:host{position:relative}devtools-editable-content{background:transparent;border:none;color:var(--override-color-recorder-input,var(--sys-color-on-surface));cursor:text;display:inline-block;line-height:18px;min-height:18px;min-width:0.5em;outline:none;overflow-wrap:anywhere}devtools-editable-content:hover,
devtools-editable-content:focus{box-shadow:0 0 0 1px var(--sys-color-divider);border-radius:2px}devtools-editable-content[placeholder]:empty::before{content:attr(placeholder);color:var(--sys-color-on-surface);opacity:50%}devtools-editable-content[placeholder]:empty:focus::before{content:""}devtools-suggestion-box{position:absolute;display:none}devtools-editable-content:focus ~ devtools-suggestion-box{display:block}.suggestions{background-color:var(--sys-color-cdt-base-container);box-shadow:var(--drop-shadow);min-height:1em;min-width:150px;overflow:hidden auto;position:relative;z-index:100;max-height:350px}.suggestions > li{padding:1px;border:1px solid transparent;white-space:nowrap;font-family:var(--source-code-font-family);font-size:var(--source-code-font-size);color:var(--sys-color-on-surface)}.suggestions > li:hover{background-color:var(--sys-color-state-hover-on-subtle)}.suggestions > li.selected{background-color:var(--sys-color-primary);color:var(--sys-color-cdt-base-container)}.strikethrough{text-decoration:line-through}
/*# sourceURL=${import.meta.resolve("./suggestionInput.css")} */`;var s=function(t,e,o,n){var c=arguments.length,l=c<3?e:n===null?n=Object.getOwnPropertyDescriptor(e,o):n,d;if(typeof Reflect=="object"&&typeof Reflect.decorate=="function")l=Reflect.decorate(t,e,o,n);else for(var u=t.length-1;u>=0;u--)(d=t[u])&&(l=(c<3?d(l):c>3?d(e,o,l):d(e,o))||l);return c>3&&l&&Object.defineProperty(e,o,l),l},j=(t,e)=>(t%e+e)%e;function w(t,e="Assertion failed!"){if(!t)throw new Error(e)}var{html:g,Decorators:D,Directives:A,LitElement:v}=R,{customElement:m,property:r,state:E}=D,{classMap:$}=A,C={hasChanged(t,e){return JSON.stringify(t)!==JSON.stringify(e)},attribute:!1},k=class extends HTMLElement{static get observedAttributes(){return["disabled","placeholder"]}set disabled(e){this.contentEditable=String(!e)}get disabled(){return this.contentEditable!=="true"}set value(e){this.innerText=e,this.#t()}get value(){return this.innerText}set mimeType(e){this.#e=e,this.#t()}get mimeType(){return this.#e}#e="";constructor(){super(),this.contentEditable="true",this.tabIndex=0,this.addEventListener("focus",()=>{this.innerHTML=this.innerText}),this.addEventListener("blur",this.#t.bind(this))}#t(){this.#e&&x.CodeHighlighter.highlightNode(this,this.#e)}attributeChangedCallback(e,o,n){switch(e){case"disabled":this.disabled=n!==null;break}}};k=s([m("devtools-editable-content")],k);var y=class t extends Event{static eventName="suggest";constructor(e){super(t.eventName),this.suggestion=e}},b=class t extends Event{static eventName="suggestioninit";listeners;constructor(e){super(t.eventName),this.listeners=e}},N=(t,e)=>t.toLowerCase().startsWith(e.toLowerCase()),a=class extends v{#e=[];constructor(){super(),this.options=[],this.expression="",this.cursor=0}#t=e=>{if(w(e instanceof KeyboardEvent,"Bound to the wrong event."),this.#e.length>0)switch(e.key){case"ArrowDown":e.stopPropagation(),e.preventDefault(),this.#o(1);break;case"ArrowUp":e.stopPropagation(),e.preventDefault(),this.#o(-1);break}switch(e.key){case"Enter":this.#e[this.cursor]&&this.#s(this.#e[this.cursor]),e.preventDefault();break}};#o(e){this.cursor=j(this.cursor+e,this.#e.length)}#s(e){this.dispatchEvent(new y(e))}connectedCallback(){super.connectedCallback(),this.dispatchEvent(new b([["keydown",this.#t]]))}willUpdate(e){e.has("options")&&(this.options=Object.freeze([...this.options].sort())),(e.has("expression")||e.has("options"))&&(this.cursor=0,this.#e=this.options.filter(o=>(this.suggestionFilter||N)(o,this.expression)))}render(){if(this.#e.length!==0)return g`<style>${p}</style><ul class="suggestions">
      ${this.#e.map((e,o)=>g`
        <li class=${$({selected:o===this.cursor})}
            @mousedown=${this.#s.bind(this,e)}
            jslog=${h.item("suggestion").track({click:!0,resize:!0})}>
          ${e}
        </li>`)}
    </ul>`}};s([r(C)],a.prototype,"options",void 0);s([r()],a.prototype,"expression",void 0);s([r()],a.prototype,"suggestionFilter",void 0);s([E()],a.prototype,"cursor",void 0);a=s([m("devtools-suggestion-box")],a);var i=class extends v{static shadowRootOptions={...v.shadowRootOptions,delegatesFocus:!0};constructor(){super(),this.options=[],this.expression="",this.placeholder="",this.value="",this.disabled=!1,this.strikethrough=!0,this.mimeType="",this.autocomplete=!0,this.addEventListener("blur",this.#o);let e=h.value().track({keydown:"ArrowUp|ArrowDown|Enter",change:!0,click:!0});this.jslogContext&&(e=e.context(this.jslogContext)),this.setAttribute("jslog",e.toString())}#e;get#t(){if(this.#e)return this.#e;let e=this.renderRoot.querySelector("devtools-editable-content");if(!e)throw new Error("Attempted to query node before rendering.");return this.#e=e,e}#o=()=>{window.getSelection()?.removeAllRanges(),this.value=this.#t.value,this.expression=this.#t.value};#s=e=>{w(e.target instanceof Node);let o=document.createRange();o.selectNodeContents(e.target);let n=window.getSelection();n.removeAllRanges(),n.addRange(o)};#i=e=>{e.key==="Enter"&&e.preventDefault()};#r=e=>{this.expression=e.target.value};#n=e=>{for(let[o,n]of e.listeners)this.addEventListener(o,n)};#l=e=>{this.#t.value=e.suggestion,setTimeout(this.blur.bind(this),0)};willUpdate(e){e.has("value")&&(this.expression=this.value)}render(){return g`<style>${p}</style>
      <style>${f}</style>
      <devtools-editable-content
        ?disabled=${this.disabled}
        class=${$({strikethrough:!this.strikethrough})}
        .enterKeyHint=${"done"}
        .value=${this.value}
        .mimeType=${this.mimeType}
        @focus=${this.#s}
        @input=${this.#r}
        @keydown=${this.#i}
        autocapitalize="off"
        inputmode="text"
        placeholder=${this.placeholder}
        spellcheck="false"
      ></devtools-editable-content>
      <devtools-suggestion-box
        @suggestioninit=${this.#n}
        @suggest=${this.#l}
        .options=${this.options}
        .suggestionFilter=${this.suggestionFilter}
        .expression=${this.autocomplete?this.expression:""}
      ></devtools-suggestion-box>`}};s([r(C)],i.prototype,"options",void 0);s([r({type:Boolean})],i.prototype,"autocomplete",void 0);s([r()],i.prototype,"suggestionFilter",void 0);s([E()],i.prototype,"expression",void 0);s([r()],i.prototype,"placeholder",void 0);s([r()],i.prototype,"value",void 0);s([r({type:Boolean})],i.prototype,"disabled",void 0);s([r({type:Boolean})],i.prototype,"strikethrough",void 0);s([r()],i.prototype,"mimeType",void 0);s([r()],i.prototype,"jslogContext",void 0);i=s([m("devtools-suggestion-input")],i);export{S as SuggestionInput};
//# sourceMappingURL=suggestion_input.js.map
