var H=Object.defineProperty;var x=(o,e)=>{for(var s in e)H(o,s,{get:e[s],enumerable:!0})};var $={};x($,{WarningErrorCounter:()=>C,WarningErrorCounterWidget:()=>p});import"./../../ui/components/icon_button/icon_button.js";import*as c from"./../../core/common/common.js";import*as y from"./../../core/host/host.js";import*as w from"./../../core/i18n/i18n.js";import*as t from"./../../core/sdk/sdk.js";import*as m from"./../../models/issues_manager/issues_manager.js";import*as D from"./../../ui/components/issue_counter/issue_counter.js";import*as i from"./../../ui/legacy/legacy.js";import*as k from"./../../ui/lit/lit.js";import*as I from"./../../ui/visual_logging/visual_logging.js";var{html:h,nothing:E,render:N}=k,u={sErrors:"{n, plural, =1 {# error} other {# errors}}",sWarnings:"{n, plural, =1 {# warning} other {# warnings}}",openConsoleToViewS:"Open Console to view {PH1}",openIssuesToView:"{n, plural, =1 {Open Issues to view # issue:} other {Open Issues to view # issues:}}"},O=w.i18n.registerUIStrings("panels/console_counters/WarningErrorCounter.ts",u),g=w.i18n.getLocalizedString.bind(void 0,O),W=(o,e,s)=>{let n=m.IssuesManager.IssuesManager.instance(),r=V=>V===0?void 0:`${V}`,{errors:a,warnings:l,issues:T,compact:b}=o,f=g(u.sErrors,{n:a}),S=g(u.sWarnings,{n:l}),d="";a&&l?d=`${f}, ${S}`:a?d=f:l&&(d=S);let v=g(u.openConsoleToViewS,{PH1:d}),U={clickHandler:c.Console.Console.instance().show.bind(c.Console.Console.instance()),accessibleName:v,compact:b,groups:[{iconName:"cross-circle-filled",text:r(a)},{iconName:"warning-filled",text:r(l)}]},K=D.IssueCounter.getIssueCountsEnumeration(n),L=`${g(u.openIssuesToView,{n:T})} ${K}`,F={clickHandler:o.showIssuesHandler,issuesManager:n,compact:b,accessibleName:L,displayMode:"OnlyMostImportant"};N(h`<div class="status-buttons"
         >${a+l?h`<icon-button
            .data=${U}
            title=${v}
            class=${"small"}
            jslog=${I.counter("console").track({click:!0})}
         ></icon-button>`:E}${T?h`<devtools-issue-counter
            class=${"main-toolbar"}
            title=${L}
            .data=${F}
            jslog=${I.counter("issue").track({click:!0})}
         ></devtools-issue-counter>`:E}</div>`,s)},p=class o extends i.Widget.Widget{setVisibility;view;throttler;updatingForTest;compact;static instanceForTest=null;constructor(e,s,n=W){super(e),this.setVisibility=s,this.view=n,this.throttler=new c.Throttler.Throttler(100),t.TargetManager.TargetManager.instance().addModelListener(t.ConsoleModel.ConsoleModel,t.ConsoleModel.Events.ConsoleCleared,this.update,this),t.TargetManager.TargetManager.instance().addModelListener(t.ConsoleModel.ConsoleModel,t.ConsoleModel.Events.MessageAdded,this.update,this),t.TargetManager.TargetManager.instance().addModelListener(t.ConsoleModel.ConsoleModel,t.ConsoleModel.Events.MessageUpdated,this.update,this),m.IssuesManager.IssuesManager.instance().addEventListener("IssuesCountUpdated",this.update,this),this.update(),o.instanceForTest=this}onSetCompactLayout(e){this.setCompactLayout(e.data)}setCompactLayout(e){this.compact=e,this.performUpdate()}updatedForTest(){}update(){this.updatingForTest=!0,this.throttler.schedule(this.performUpdate.bind(this))}get titlesForTesting(){let e=this.contentElement.querySelector("icon-button")?.shadowRoot?.querySelector("button");return e?e.getAttribute("aria-label"):null}showIssues(){y.userMetrics.issuesPanelOpenedFrom(2),i.ViewManager.ViewManager.instance().showView("issues-pane")}async performUpdate(){let e=t.ConsoleModel.ConsoleModel.allErrors(),s=t.ConsoleModel.ConsoleModel.allWarnings(),r=m.IssuesManager.IssuesManager.instance().numberOfIssues();this.view({compact:this.compact,errors:e,warnings:s,issues:r,showIssuesHandler:this.showIssues.bind(this)},{},this.contentElement),this.setVisibility(!!(e||s||r)),i.InspectorView.InspectorView.instance().toolbarItemResized(),this.updatingForTest=!1,this.updatedForTest()}},M,C=class o{toolbarItem;constructor(){let e=document.createElement("devtools-widget"),s=new i.Toolbar.ToolbarItemWithCompactLayout(e);s.setVisible(!1);let n=new p(e,s.setVisible.bind(s));s.addEventListener("CompactLayoutUpdated",n.onSetCompactLayout,n),this.toolbarItem=s}item(){return this.toolbarItem}static instance(e={forceNew:null}){let{forceNew:s}=e;return(!M||s)&&(M=new o),M}};export{$ as WarningErrorCounter};
//# sourceMappingURL=console_counters.js.map
